ARG REPOS_IMAGE=quay.io/fedora/fedora@sha256:8938dce2600de0b78f5ef8d1541192f207fdafb7414d83957f6687147aa8998b
ARG CONFIG_BUILDER=localhost/container-rootfs-builder:latest
ARG FEDORA_RELEASE=44

FROM ${REPOS_IMAGE} AS repos
FROM ${CONFIG_BUILDER} AS compose
ARG FEDORA_RELEASE
RUN --mount=from=repos,src=/,target=/repos,rw \
    /usr/local/bin/container-rootfs-builder build-rootfs \
      --from=quay.io/fedora/fedora-bootc:${FEDORA_RELEASE} \
      --source-root=/repos --source-root-rw --target=/target-rootfs

FROM scratch
COPY --from=compose /target-rootfs /
LABEL containers.bootc=1
LABEL ostree.bootable=1
ENV container=oci
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
