ARG REPOS_IMAGE=quay.io/fedora/fedora@sha256:80d49c6c7c4303efb5eebc0317e343588d5d482146ca2be48eb82494d2a83060
ARG CONFIG_BUILDER=localhost/container-rootfs-builder:latest
ARG FEDORA_RELEASE=44
ARG ATOMIC_VARIANT=silverblue

FROM ${REPOS_IMAGE} AS repos
FROM ${CONFIG_BUILDER} AS compose
ARG ATOMIC_VARIANT
ARG FEDORA_RELEASE
RUN --mount=from=repos,src=/,target=/repos,rw \
    /usr/local/bin/container-rootfs-builder build-rootfs \
      --from=quay.io/fedora/fedora-${ATOMIC_VARIANT}:${FEDORA_RELEASE} \
      --source-root=/repos --source-root-rw --target=/target-rootfs

# Experimental filesystem rootfs only; this does not assert bootability.
FROM scratch
COPY --from=compose /target-rootfs /
