ARG REPOS_IMAGE=quay.io/fedora/fedora@sha256:80d49c6c7c4303efb5eebc0317e343588d5d482146ca2be48eb82494d2a83060
ARG CONFIG_BUILDER=localhost/container-rootfs-builder:latest
ARG FEDORA_RELEASE=44

FROM ${REPOS_IMAGE} AS repos
FROM ${CONFIG_BUILDER} AS compose
ARG FEDORA_RELEASE
RUN --mount=from=repos,src=/,target=/repos,rw \
    /usr/local/bin/container-rootfs-builder build-rootfs \
      --from=quay.io/fedora/fedora-bootc:${FEDORA_RELEASE} \
      --source-root=/repos --source-root-rw --target=/target-rootfs

FROM scratch
COPY --from=compose /target-rootfs /
LABEL containers.bootc=1
LABEL ostree.bootable=1
ENV container=oci
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
